### PR TITLE
Prepare for Erlang/OTP 22

### LINKED ISSUE #502: Prepare for Erlang/OTP 22
Add version 22 to rebar.config
Handle changed logging in gen_fsm and gen_statem in stdlib-3.9

### PR DESCRIPTION
**Pull request by vikger**
Closes #502

### CODE REVIEW

**Comment by vikger** [comment]
Verified locally on Erlang/OTP 22.0 and 22.0.1.

**Comment by mrallen1** [comment]
Looks great - would you mind adding 22.0 and dropping 19 from the .travis.yml file in this PR too?

**Comment by vikger** [comment]
The .travis.yml update is done, too.

**Comment by mrallen1** [comment]
Thanks so much!

**Comment by mrallen1** [comment]
I'll need to roll a new release later today

**Comment by mrallen1** [comment]
Released 3.7.0 to hex and tagged here. Thanks!

**Pull request merged**
