### PR TITLE
Remove code which supports R15

### LINKED ISSUE #399: Remove code which supports R15
As R15 support has been officially deprecated, remove R15 code from the codebase.

### PR DESCRIPTION
**Pull request by puzza007**
Fixes #399 

Perhaps the comments for https://github.com/erlang-lager/lager/blob/master/src/error_logger_lager_h.erl#L403 and https://github.com/erlang-lager/lager/blob/master/src/error_logger_lager_h.erl#L477 need updating but aside from that I think I've got it all.

geas output

```
~/src/lager (remove-r15) $ rebar3 geas
===> Verifying dependencies...
===> Compiling lager
   R15                   20.2       Geas database
---Min--------Arch-------Max----------------------------------------------------
                                    goldrush
   17.0                             lager
                                    goldrush
   17.0                             lager
   17.0                             lager
--------------------------------------------------------------------------------
   17.0                  20.2       Global project

./_build/default/lib/lager/ebin/error_logger_lager_h.beam
R16B      application:get_env/3

./_build/default/lib/lager/ebin/lager.beam
R16B01    lists:filtermap/2

./_build/default/lib/lager/ebin/lager_app.beam
R16B      application:get_env/3

./_build/default/lib/lager/ebin/lager_stdlib.beam
R16B      application:get_env/3

./_build/default/lib/lager/ebin/lager_sup.beam
R16B      application:get_env/3

./_build/default/lib/lager/ebin/lager_trunc_io.beam
17.0      erlang:map_size/1

./_build/test/lib/lager/ebin/error_logger_lager_h.beam
R16B      application:get_env/3

./_build/test/lib/lager/ebin/lager.beam
R16B01    lists:filtermap/2

./_build/test/lib/lager/ebin/lager_app.beam
R16B      application:get_env/3

./_build/test/lib/lager/ebin/lager_stdlib.beam
R16B      application:get_env/3

./_build/test/lib/lager/ebin/lager_sup.beam
R16B      application:get_env/3

./_build/test/lib/lager/ebin/lager_trunc_io.beam
17.0      erlang:map_size/1

./_build/test/lib/lager/ebin/lager_util.beam
R16B      file:list_dir_all/1

./_build/test/lib/lager/test/crash.beam
18.0      proc_lib:stop/1

./_build/test/lib/lager/test/lager_test_function_transform.beam
18.0      erlang:monotonic_time/0
```

### CODE REVIEW

**Comment by Vagabond** [comment]
Oh, nice! Given our support policy of 'last three major versions' this looks great.

**Comment by puzza007** [comment]
I'm just trying to figure out what's up with that one failing test in 18.3. I can't reproduce it locally.

**Comment by Vagabond** [comment]
It's a race condition, I think the Erlang 18 builder is on a slow/overprovisioned machine.

**Comment by puzza007** [comment]
👍 ok cool. I think it's good to go then.

**Comment by Vagabond** [comment]
I wonder if removing `lager_app:get_env` is a backwards incompatible change? It was an exported function, so some other code might be using it...

**Comment by puzza007** [comment]
Ah yes. Ok I'll add it back as a wrapper for `application:get_env` to save a version bump.

**Comment by mrallen1** [comment]
IIRC, @macintux added that function expressly to support R15 compatibility. But as things are, this is a great contribution. Thank you!!

**Comment by mrallen1** [comment]
Wanted to rerun the 18 test but YOLO

**Pull request merged**
