### PR TITLE
Add config for suppress supervisors start/stop

### PR DESCRIPTION
**Pull request by artemeff**

### CODE REVIEW

**Comment by mrallen1** [comment]
Is this change just to avoid "spammy" supervisor start up messages?

**Comment by artemeff** [comment]
@mrallen1 yes :)

**Comment by mrallen1** [comment]
Would you please use `lager_app:get_env/3` instead of `application:get_env/2` in this PR?

**Comment by waisbrot** [comment]
Awesome! How about changing the README, too, to mention the `suppress_suprevisor_start_stop` setting?

**Comment by mrallen1** [comment]
Yep, good idea :)

**Comment by artemeff** [comment]
@mrallen1 @waisbrot done :)

also fix config key typo:

```diff
-suppress_suprevisor_start_stop
+suppress_supervisor_start_stop
```

😁

**Comment by artemeff** [comment]
@mrallen1 ping :shipit:

**Comment by macintux** [comment]
My apologies, I should be free to look at this next week.

**Comment by artemeff** [comment]
🏓

**Comment by mrallen1** [comment]
LGTM 👍

**Pull request merged**
