### PR TITLE
Fix for incorrectly counting dropped messages

### PR DESCRIPTION
**Pull request by mrallen1**
Lager changes the error level of supervisor progress messages from info to debug. This is done after the hwm checking changes the received message count. This PR implements a fix by removing one from the count if no message was sent.

Closes: #496

### CODE REVIEW

**Comment by lukebakken** [comment]
This appears to fix the issue. I have a script that generates many errors in RabbitMQ. You can see the log file contents before and after this patch is applied. The messages about `lager_error_logger_h` disappear:

```
2019-04-18 13:33:17.006 [warning] <0.127.0> lager_error_logger_h dropped 1361 messages in the last second that exceeded the limit of 1000 messages/sec
2019-04-18 13:33:18.000 [warning]  lager_file_backend dropped 858 messages in the last second that exceeded the limit of 50 messages/sec
2019-04-18 13:33:18.000 [warning] <0.127.0> lager_error_logger_h dropped 1270 messages in the last second that exceeded the limit of 1000 messages/sec
2019-04-18 13:33:19.001 [warning]  lager_file_backend dropped 911 messages in the last second that exceeded the limit of 50 messages/sec
2019-04-18 13:33:19.001 [warning] <0.127.0> lager_error_logger_h dropped 1390 messages in the last second that exceeded the limit of 1000 messages/sec
2019-04-18 13:33:20.000 [warning]  lager_file_backend dropped 835 messages in the last second that exceeded the limit of 50 messages/sec
2019-04-18 13:33:20.001 [warning] <0.127.0> lager_error_logger_h dropped 1227 messages in the last second that exceeded the limit of 1000 messages/sec
2019-04-18 13:33:21.000 [warning]  lager_file_backend dropped 986 messages in the last second that exceeded the limit of 50 messages/sec
2019-04-18 13:33:21.001 [warning] <0.127.0> lager_error_logger_h dropped 1589 messages in the last second that exceeded the limit of 1000 messages/sec
2019-04-18 13:33:22.114 [warning]  lager_file_backend dropped 331 messages in the last second that exceeded the limit of 50 messages/sec
```

Applied patch...

```
2019-04-18 13:38:48.000 [warning]  lager_file_backend dropped 570 messages in the last second that exceeded the limit of 50 messages/sec
2019-04-18 13:38:49.001 [warning]  lager_file_backend dropped 875 messages in the last second that exceeded the limit of 50 messages/sec
2019-04-18 13:38:50.000 [warning]  lager_file_backend dropped 926 messages in the last second that exceeded the limit of 50 messages/sec
2019-04-18 13:38:51.000 [warning]  lager_file_backend dropped 877 messages in the last second that exceeded the limit of 50 messages/sec
2019-04-18 13:38:52.001 [warning]  lager_file_backend dropped 861 messages in the last second that exceeded the limit of 50 messages/sec
2019-04-18 13:38:53.000 [warning]  lager_file_backend dropped 923 messages in the last second that exceeded the limit of 50 messages/sec
2019-04-18 13:38:54.108 [warning]  lager_file_backend dropped 49 messages in the last second that exceeded the limit of 50 messages/sec
```

**Comment by mrallen1** [comment]
Happy to merge it if the tests become reliable.

**Comment by lukebakken** [comment]
Well that's annoying, `rebar3 eunit` works just fine on my machine.

**Comment by lukebakken** [comment]
OK I'm seeing at least one of the same failures using `19.3.6.12`, maybe I can figure it out.

**Comment by lukebakken** [comment]
Please see #499. Working on fixing the tests now. Thanks @mrallen1

**Pull request merged**
