### PR TITLE
Enable Thumbs

### PR DESCRIPTION
**Pull request by ooshlablu**

### CODE REVIEW

**Comment by ooshlablu** [comment]
thumbot retry

**Comment by davidx** [comment]
+1

**Comment by mrallen1** [comment]
@ooshlablu should this PR be aimed at the basho fork? :)

**Comment by Vagabond** [comment]
What the hell is this?

**Comment by macintux** [comment]
Thumbs is an in-house replacement for Bors, which has been...unreliable.

I imagine @mrallen1 is right, this probably predates the transfer of lager to a new home.

**Pull request closed without merging**
