### PR TITLE
rotation - default log file not deleted

### LINKED ISSUE #402: Lager does not create a new log file immediately after the old log file is rotated
After log rotation is not created new empty file.
This is required when used monitoring tools like zabbix to check file size.

Could you add ability to create new empty file after  log rotation.
P.S. As workaround may be used external log rotation.

```
[root@kazoo-app02 log]# ls -l
total 16920
-rw-r--r-- 1 kazoo daemon 2496086 Apr 12 07:02 console.log
-rw-r--r-- 1 kazoo daemon 8534767 Apr 11 23:59 console.log.1
-rw-r--r-- 1 kazoo daemon 5485187 Apr 10 23:59 console.log.3
-rw-r--r-- 1 kazoo daemon  675063 Apr 10 00:00 console.log.4
-rw-r--r-- 1 kazoo daemon       0 Apr 11 15:40 crash.log.1
-rw-r--r-- 1 kazoo daemon   69156 Apr  8 09:56 crash.log.4
-rw-r--r-- 1 kazoo daemon    2106 Apr 11 15:40 error.log.1
-rw-r--r-- 1 kazoo daemon   35375 Apr  8 09:56 error.log.4
```

### PR DESCRIPTION
**Pull request by shamis**
fixes #402

### CODE REVIEW

**Comment by Vagabond** [comment]
Oh, this is great! Very simple solution to the problem.

I will push something with a few changes shortly (and try to credit you on the commit).

**Comment by Vagabond** [comment]
Take a look at https://github.com/erlang-lager/lager/commit/8d7eecda49d13b87a28efd5fb7f77185be263515 and see what you think.

**Comment by shamis** [comment]
Thanks. Everything looks good. But do we need to return on error of `rotate_logfile(File, 1)` ?

**Comment by shamis** [comment]
I think file descriptor has to be closed here https://github.com/erlang-lager/lager/commit/8d7eecda49d13b87a28efd5fb7f77185be263515#diff-1241b45549162d6b3da7af338c645bd3R78

**Comment by Vagabond** [comment]
You're right about `rotate_logfile(File, 1)`, I realized that after I pushed.

The file descriptor will be closed by the garbage collector, we don't really have to worry about it.

I will push an update commit though.

**Comment by Vagabond** [comment]
Ok, pushed an update. Thanks again for the contribution. Will close this issue.

**Comment by mrallen1** [comment]
Oh, thanks so much @shamis. This issue has been open for a long long time!

**Comment by shamis** [comment]
you are welcome. happy to help

**Pull request closed without merging**
