### PR TITLE
Support gen_statem in error logger

### PR DESCRIPTION
**Pull request by priestjim**
Add a simple case to support gen_statem crashes, since they generate the
same message in error_logger but not the same returned state.

### CODE REVIEW

**Comment by pj-splunk** [comment]
@nickelization care to take a look on this one as well?

**Comment by mrallen1** [comment]
This is really nice. Thank you!

Would you mind adding a test [here](https://github.com/erlang-lager/lager/blob/master/test/lager_test_backend.erl#L902) so I can get this merged?

**Comment by priestjim** [comment]
@mrallen1 how should the test be implemented? It feels like it's just a case of gen_fsm messages vs gen_statem messages and gen_fsm crash capturing is not really tested in lager

**Comment by mrallen1** [comment]
You know, you're right! I had thought we covered it, but we haven't!

**Comment by mrallen1** [comment]
I pushed a new branch `fsm_test` which has a gen_fsm and gen_statem that crash and conditionally compile statem on OTP 19+ only. So my plan is to merge your PR into that branch and then put at least one simple test in.

**Comment by mrallen1** [comment]
I'm going to close this now as I have green tests on #391. Thanks for your patch!

**Pull request closed without merging**
