### PR TITLE
Fix for incorrectly counting dropped messages

### LINKED ISSUE #496: Lager incorrectly counting dropped messages from Error Logger
Hi, 

I am currently seeing a lot of messages in the log file with error_logger_lager_h: 

```
15:23:09.000 [warning] lager_error_logger_h dropped 198 messages in the last second that exceeded the limit of 50 messages/sec
15:23:10.005 [warning] lager_error_logger_h dropped 217 messages in the last second that exceeded the limit of 50 messages/sec
```

This is very annoying, mainly because it is misleading but also can mislead the shaper to drop messages which would have been important. 

The reason this is happening because the progress reports from supervisors are changed from info to debug, so nothing is visible, however the code still performs the shaping on the logs. 

See here: 

https://github.com/erlang-lager/lager/blob/94f4cd5d4a6797727bee49e86ab1c1f60a039389/src/error_logger_lager_h.erl#L341-L348

As you can see the line 348 reports the log with debug, however at this point the `check_hwm` already added one to `mps`. 

https://github.com/erlang-lager/lager/blob/06f676aad8ed823b7838a70288cd4d13b5a25ede/src/lager_util.erl#L505-L507

I am open to fix it, let me know if you have any method in mind. My thinking would be that `fn log_event` returns how many messages were added and then we can change the `mps`, or it returns `true` or `false` if there were any messages sent, and if there was not we can restore the `mps` to the previous value, according to the `?SHOULD_LOG` macro. 

Thanks

### PR DESCRIPTION
**Pull request by lukebakken**
Includes and supersedes #497 

Fixes #496

### CODE REVIEW

**Comment by lukebakken** [comment]
@mrallen1 tests are fixed. There were differences due to application startup times between my workstation and Travis CI.

**Comment by mrallen1** [comment]
That's really dope. Thanks so very much. :candy:

**Comment by mrallen1** [comment]
just pushed 3.6.10 to hex - thank you very much! 🥇 ❤️

**Comment by lukebakken** [comment]
Thanks @mrallen1 !

**Pull request merged**
